include: package:flutter_lints/flutter.yaml

linter:
  rules: # 규칙 느슨하게 만들어줌
    prefer_const_constructors: false
    prefer_final_fields: false
    use_key_in_widget_constructors: false
    prefer_const_literals_to_create_immutables: false
    prefer_const_constructors_in_immutables: false
    avoid_print: false # log 권장